name: "Google Photos Mobile Client"
description: "Google Photos client based on reverse engineered mobile API."
version: "1.0.13"
slug: "gpmc_addon"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
options:
  auth_data: ""
  path: "/media"
  album: ""
  recursive: false
  delete_from_host: false
  log_level: "WARNING"
  batch_size: 1000
schema:
  auth_data: str
  path: str
  album: str?
  recursive: bool
  delete_from_host: bool
  log_level: "match(DEBUG|INFO|WARNING|ERROR|CRITICAL)"
  batch_size: "int?"
map:
  - share:rw
  - media:rw
